# Generated by Django 4.2.4 on 2023-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0004_alter_movie_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="currency",
            field=models.CharField(
                choices=[("E", "Euro"), ("D", "Dollars"), ("R", "Rubles")], default="R", max_length=1
            ),
        ),
    ]
