# Generated by Django 4.2.4 on 2023-10-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0009_movie_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(choices=[("M", "Мужчина"), ("F", "Женщина")], default="M", max_length=1)),
            ],
        ),
    ]
