# Generated by Django 4.2.4 on 2023-10-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movie_app", "0010_actor"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(to="movie_app.actor"),
        ),
    ]
